baseurl = "http://negge.fi"
languageCode = "en-us"
title = "Sam Stenvall"
theme = "strange-case"
author = "Sam Stenvall"
canonifyurls = true
paginate = 5

pygmentsuseclasses = false
pygmentsstyle = "monokai"
pygmentsoptions = "linenos=true"

[pygments_options]
  tabsize = 4
  
[params]
    colorScheme = "scheme-darkbrown"
    DateFormat = "2 Jan 2006"
    description = "Biography, portfolio, blog"
    sidebarDescription = "A Hugo Theme built with Bootstrap"
    sidebarFreeText = ""

[[menu.main]]
    name = "Portfolio"
    post = "<span class='glyphicon glyphicon-briefcase'></span>"
    url = "/page/portfolio"
    weight = 10
    
[[menu.main]]
    name = "Biography"
    post = "<span class='glyphicon glyphicon-user'></span>"
    url = "/page/biography"
    weight = 20
    
[[menu.main]]
    name = "Blog"
    post = "<span class='glyphicon glyphicon-book'></span>"
    url = "/blog"
    weight = 30
